### Site metadata ###

site_name: mkrgen Docs
site_description: Official documentation for mkrgen project
site_url: https://docs.mkrgen.dev/

repo_url: https://github.com/noxymon-mekari/mkrgen
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - toc.flow
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - mkrgen UI: blueprint-ui.md
  - Project creation & default config:
    - Project init: creating-project/project-init.md
    - Makefile: creating-project/makefile.md
    - Air: creating-project/air.md
  - mkrgen Core:
    - Frameworks: blueprint-core/frameworks.md
    - DB Drivers: blueprint-core/db-drivers.md
  - Advanced Flag:
    - AF Usage: advanced-flag/advanced-flag.md
    - HTMX and Templ: advanced-flag/htmx-templ.md
    - Tailwind CSS: advanced-flag/tailwind.md
    - GoReleaser & GoTest CI: advanced-flag/goreleaser.md
    - Websocket: advanced-flag/websocket.md
    - Docker: advanced-flag/docker.md
    - React & Vite (TypeScript): advanced-flag/react-vite.md
    - Kafka Consumer: advanced-flag/kafka.md
    - Worker: advanced-flag/worker.md
    - Redis Integration: advanced-flag/redis.md
    - Swagger Documentation: advanced-flag/swagger.md
  - Testing endpoints: 
    - Server: endpoints-test/server.md
    - DB Health Endpoints: 
       - SQL DBs: endpoints-test/sql.md
       - Redis: endpoints-test/redis.md
       - MongoDB: endpoints-test/mongo.md
       - ScyllaDB: endpoints-test/scylladb.md
    - Websocket: endpoints-test/websocket.md
    - Web Endpoint: endpoints-test/web.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/noxymon-mekari/mkrgen
        name: GitHub
    generator: false

copyright: Copyright &copy; 2025 noxymon-mekari
